version: '3'
services:
  # ZABBIX
  zabbix-app:
    image: zabbix/zabbix-appliance:latest
    container_name: zabbix-app
    ports:
      - 10051:10051
      - 8030:80
    volumes:
      - ./db:/var/lib/mysql:rw
    networks:
      default:
        ipv4_address: 172.24.0.4
networks:
  default:
    external:
      name: so-monitoring