version: '3'
services:
  # APP
  app:
    volumes:
      # Main app
      - ./app:/app
      # to run systemctl
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    build: app 
    working_dir: /app
    privileged: true
    ports: 
      # App API port
      - 3000:3000
      # Nagios NRPE Agent port
      - 5666:5666
      # Zabbix Agent port
      - 10050:10050
  # WORKER
  worker:
    build: worker
    volumes:
      - ./worker:/worker
    working_dir: /worker
    command: "bash -c 'cat /etc/os-release | grep PRETTY_NAME && python -u ./worker.py'"
    depends_on: 
      - app
networks:
  default:
    external:
      name: so-monitoring