version: '3'
services:
  # APP
  app:
    volumes:
      - ./app:/app
      - /run/systemd/system:/run/systemd/system
      # - /bin/systemctl:/bin/systemctl
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      # - /sys/fs/cgroup/:/sys/fs/cgroup:ro
    build: app 
    working_dir: /app
    privileged: true
    ports: 
      - 3000:3000
  # WORKER
  worker:
    build: worker
    volumes:
      - ./worker:/worker
    working_dir: /worker
    command: "bash -c 'cat /etc/os-release | grep PRETTY_NAME && python -u ./worker.py'"
    depends_on: 
      - app