version: '3'
services:
  # APP
  app:
    volumes:
      - ./app:/app
    build: app 
    working_dir: /app
    privileged: true
    ports: 
      - 3000:3000
  # WORKER
  worker:
    build: worker
    volumes:
      - ./worker:/worker
    working_dir: /worker
    command: "bash -c 'cat /etc/os-release | grep PRETTY_NAME && python -u ./worker.py'"
    depends_on: 
      - app