version: '3'
services:
  # NAGIOS
  nagios-app:
    container_name: nagios
    image: jasonrivers/nagios:latest
    ports:
      - 8020:80
    volumes:
      - ./db:/var/lib/mysql:rw
      - ./config:/nagios-config/:rw
    networks:
      default:
        ipv4_address: 172.24.0.2
networks:
  default:
    external:
      name: so-monitoring