version: '3'
services:
  # NAGIOS
  nagios-app:
    container_name: nagios
    image: jasonrivers/nagios:latest
    ports:
      - 8020:80
      - 5666:5666
    volumes:
      - ./db:/var/lib/mysql:rw
networks:
  default:
    external:
      name: so-monitoring