version: '3'
services:
  # PANDORA
  pandora-app:
    image: pandorafms/pandorafms
    container_name: pandora-app
    ports:
      - 41121:41121
      - 8010:80
    networks:
      default:
        ipv4_address: 172.24.0.3
networks:
  default:
    external:
      name: so-monitoring